version: '3.8'

services:
  rt-frontend:
    image: lobe-v2
    container_name: lobe-v2
    ports:
      - "3210:3210"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rt-network

networks:
  rt-network:
    driver: bridge